package html.parser;

public enum TokensId {
    EOF, HTML, HTMLCLOSE, HEADOPEN, HEADCLOSE, TITLEOPEN, TITLECLOSE, LINKOPEN, BODYOPEN, BODYCLOSE, H1OPEN, H1CLOSE, H2OPEN, H2CLOSE, POPEN, PCLOSE, BOPEN, BCLOSE, IOPEN, ICLOSE, UOPEN, UCLOSE, TAGCLOSE, PROPERTY, EQUAL, H3CLOSE, H3OPEN, VALUE, CONTENT
}
