package css.parser;

public enum TokensId {
	EOF, OPENBRACKET, CLOSEBRACKET, SEMICOLON, COLON, IDENT, COLOR, FONTSIZE, TEXTALIGN, FONTSTYLE, BLACK, BLUE, GREEN, RED,
	CENTER, RIGHT, LEFT, NORMAL, ITALIC, BOLD, UNDERLINED, SIZE
}
